package QuizServer;


import QuizServer.Assets.Question;

/**
 *
 * It manipulates the QuizServerModel by taking inputs from a user.
 *
 * It uses a QuizAssetFactory to ensure the creation of a quiz and questions is done correctly.
 *
 * It also builds the Quiz Assets required to create a
 * Quiz on the server side (a QuestionSet, an AnswerSet)

 *
 * It should be constructed with a QuizServerModel, QuizAssetFactory and a QuizView.
 *
 * Variables to consider, a QuestionSet, AnswerSet
 */
public interface QuizController {

    /**
     * takes the input from a user and verifies and creates a quiz
     * @return an id generated by calling on a quizFactory
     */
    public int createQuizSequence();

    /**
     * The user declares their name
     */
    public void setQuizAuthor();

    /**
     * The user declares their quiz's name
     */
    public void setQuizName();

    /**
     * The user inputs a question and answer that
     * is added to the question and answer set via the createAQuestion method
     */
    public void createQuestionAndAnswer();

    /**
     * Used by createQuestionAndAnswer() to package a question
     * and add it to the QuestionSet
     * @return Question
     */
    public Question packQuestion(String[] ansChoices, int[] correctAnswer);

    /**
     *
     * @return the set of questions created
     */
    public Question[] returnQuestionSet();

    /**
     *
     * @return the Array of correct answers the user generated
     */
    public int[] returnCorrectAnswers();
}
